# наш образ работает на python 3.11
FROM python:3.11

# создаем директорию на образе и копируем в нее все наше приложение
WORKDIR /src/app

COPY . ./
COPY ./requirements.txt ./

# запускаем установку библиотек и файлы приложения
RUN pip install --no-cache-dir -r requirements.txt

CMD [ "python" , "server.py" ] 